### ISSUE TITLE
Create Data Visualization Web App 

### ISSUE THREAD

**Issue by BenTheElder** [ChelsiAlise/workingdogdatadash#11]
User Story(ies):
Canine Companion Researchers would be able to visualize dog’s data. Canine Companion Staff would be able to easily run the product without much technical skill.

**Comment by BenTheElder** [comment]
See: #1, #2, #3, #4, #5, #6, #7, #8, #9, #10 ...

**Comment by ChelsiAlise** [comment]
Ignore the issue (created in error)

**Comment by BenTheElder** [comment]
See Sprint # 1 instead.
