### ISSUE TITLE
As a University Researcher/Canine Companions Researchers I want to  be able to visualize a dog’s data so I can analyze specific dogs I care about and present my study and dissertation with a clear and sound data backing.

### ISSUE THREAD

**Issue by william7hsu** [ChelsiAlise/workingdogdatadash#12]
# **Story/Task Detail**

- [x] Able to visualize different dog data

- [x] Able to display them in different graph forms

- [x] Graphs are intuitive and easy to understand

# **Acceptance Scenarios**

Given: the user has selected bar graph and data stat.

When: the user clicks the button to generate a graph.

Then: A bar graph is created.

Given: the user has selected bar graph and an invalid data.

When: the user clicks the button to generate a graph.

Then: A prompt will display invalid data.

# **Acceptance Scenarios**

Client has approved of the graph creation, code has been merged to the master branch

**Comment by william7hsu** [comment]
Bar graph custom functionality fully working. Able to do bar graphs on specific types of data for all dogs. Also able to compare different attributes of all the dogs in double bar graphs. Also added the ability to do pie graphs.

**Comment by ChelsiAlise** [comment]
Need to:

- Create master detail page format so users can expand/de-expand side bar
- remove unnecessary example graphs
- add statistical analysis page "coming soon"
- make labeling of axes on chart clearer
- show zoom & filter functionality

**Comment by BenTheElder** [comment]
Noting that #50 is the current PR for this.

**Comment by BenTheElder** [comment]
This is technically done. Closing.
