### ISSUE TITLE
As a EVERYONE I want to login to/logout of the system with my gatech/CCI email  so I can have access to the site via a secure route.

### ISSUE THREAD

**Issue by william7hsu** [ChelsiAlise/workingdogdatadash#13]
# **Story/Task Details**

- [x] Create working login with cci or gatech emails

- [x] Make login secure

- [x] Login page functionality, redirects, cookies etc

# **Acceptance Test Scenario**

Given: A user enters a valid username email and password

When: The user presses the login button

Then: The user will be redirected to the correct working dog data dash page

Given: A user enters a invalid username email and password

When: The user presses the login button

Then: The user will be prompted to reenter information because user or pass was invalid
# **Done Done Criteria**
Client has approved login page. Login is secure and easy to use. Code has been merged into master.

**Comment by BenTheElder** [comment]
I already basically did this last semester. The rest of what should happen here besides logout will be part of #14.
