### ISSUE TITLE
As a University Researcher I want to download/save processed results & graphs so I can use them in documents

### ISSUE THREAD

**Issue by jedmpaz** [ChelsiAlise/workingdogdatadash#15]
# Story/Task Details

- [x] Create button that allows users to download graphs

- [ ] Add button to graph creation page

# Acceptance Test Scenario

Given: A user has created a graph

When: The user clicks the download/save button

Then: The created graph will be downloaded

# Done Done Criteria

Page UI approve, Functionality tested and passed, Code has been merged into master.

**Comment by ChelsiAlise** [comment]
This functionality already comes implemented in high charts, hence this user story is complete. No code needed to be added. 

To test for your self .. click hamburger icon at top right of charts and you will see the following download options 
<img width="528" alt="screen shot 2017-01-27 at 2 25 07 am" src="https://cloud.githubusercontent.com/assets/5757090/22363349/d981e614-e437-11e6-8acc-6144a659da50.png">

**Comment by BenTheElder** [comment]
If this functionality already exists then perhaps it shouldn't be part of
the sprint?

**Comment by BenTheElder** [comment]
We either need to check the second check list item or reopen this.

**Comment by BenTheElder** [comment]
This is actually open because not all of the graphs have the save button on the dash that is live running right now from current master.
