### ISSUE TITLE
As a Canine Companions user I want to run the product on any browser so I can use it with all various available CCI computers

### ISSUE THREAD

**Issue by jedmpaz** [ChelsiAlise/workingdogdatadash#16]
# Story/Task Details

- [ ] Allow functionality with any browser

# Acceptance Test Scenario

Given: A user is using their browser of choice

When: The user accesses the application

Then: The user has no problems using the application

# Done Done Criteria

Functionality in major browsers tested, Code has been merged into master.

**Comment by ChelsiAlise** [comment]
<img width="1030" alt="screen shot 2017-03-10 at 12 14 19 pm" src="https://cloud.githubusercontent.com/assets/5757090/23805311/613edd40-058b-11e7-89eb-89beb2c5d6f8.png">

High charts takes care of browser capabilities as shown in the screenshot above of their documentation. Closing this issue.
