### ISSUE TITLE
 As a University Researcher/Canine Companions Researchers I want to utilize outcome data in the system so I can compare the outcome data against other data that was previously collected 

### ISSUE THREAD

**Issue by william7hsu** [ChelsiAlise/workingdogdatadash#18]
# **Story/Task Detail**
- [x]  Able to integrate outcome data into our data set.

- [ ] Able to compare the different outcome data of different dogs
Edit: the above bullet should probably be part of #28, #29, etc.

# **Acceptance Scenarios**

Given: a researcher searches the dogs name

When: The researcher clicks the button

Then: The dogs outcome data is presented

Given: A researcher wants to compare two outcome data.

When: The researcher searches two dog names

Then: It compares the two outcome data

# **Acceptance Scenarios**
The client is able to find the outcome data of all the dogs. The outcome data itself is integrated correctly with the rest of the dataset.

**Comment by BenTheElder** [comment]
The first check will be done when #45 is merged and the data is uploaded.
The second check seems to be part of the front-end UX and redundant with #31, #28 ...

**Comment by BenTheElder** [comment]
This is partially done. The data is integrated with the system, but the front end still needs to utilize it.

**Comment by BenTheElder** [comment]
#28 seems to cover the remainder of this better actually. Marking the rest of this done as a dupe.
