### ISSUE TITLE
As a University Researcher/Canine Companions Researchers I want to create customized graphs from the data so I can further analyze specific groups/datasets i'm interested in 

### ISSUE THREAD

**Issue by jedmpaz** [ChelsiAlise/workingdogdatadash#19]
# Story/Task Details

- [x] Menus for options for graph parameters
- [ ] Single page for graphs
- [ ] Multiple graph types working

# Acceptance Test Scenario

Given: A user selects parameters

When: The user creates a graph

Then: The appropriate graph is produced

Given: A user doesn't select one or more parameters

When: The user creates a graph

Then: No graph is created and the user is notified to select all required fields

# Done Done Criteria

Client approves graph types and appearance, All graph types work, Code has been merged into master.

**Comment by BenTheElder** [comment]
This has been done since before sprint one. More specific settings will be covered by #21.
