### ISSUE TITLE
As a Researchers I want to have the ability to compare dogs using multiple, specific parameters so I can more easily analyze the data from dogs from different regions

### ISSUE THREAD

**Issue by jedmpaz** [ChelsiAlise/workingdogdatadash#21]
# Story/Task Details

- [ ] Menus on graph page include options to select all possible parameters

# Acceptance Test Scenario

Given: A user selects parameters

When: The user creates a graph with selected parameters

Then: The appropriate graph is produced

Given: A user doesn't select one or more parameters

When: The user creates a graph

Then: No graph is created and the user is notified to select all required fields

# Done Done Criteria

Client approves graph types and appearance, All graph types work, Code has been merged into master.

**Comment by ChelsiAlise** [comment]
This was handled in a previous issue. Closing.
