### ISSUE TITLE
As a Researcher I want to view data based on specific attributes or over ranges like time so I can compare data sets over these ranges and/or attributes

### ISSUE THREAD

**Issue by jedmpaz** [ChelsiAlise/workingdogdatadash#22]
# Story/Task Details

- [ ] Graph page includes option selecting attributes in addition to dogs

# Acceptance Test Scenario

Given: A user selects an attribute to view a graph of

When: The user creates graph

Then: The graph is created and displayed

Given: A user doesn't select an attribute

When: The user creates a graph

Then: No graph is created and the user is notified

# Done Done Criteria

Functionality with graphs work, client approves page, Code has been merged into master.

**Comment by ChelsiAlise** [comment]
This was handled in a previous Sprint and issue. Closing.
