### ISSUE TITLE
As a University Researcher I want to  view the raw data  so I can utilize this raw data for my research

### ISSUE THREAD

**Issue by jedmpaz** [ChelsiAlise/workingdogdatadash#27]
# Story/Task Details

- [x] Page for viewing raw data

# Acceptance Test Scenario

Given: A user selects a dog or attribute

When: The user clicks button to view data

Then: The raw data in the form of a spreadsheet is show

Given: A user doesn't select any dog or attribute

When: The user clicks a button to view data

Then: No raw data is shown

# Done Done Criteria

Functionality works, client approves page, code has been merged into master.

**Comment by BenTheElder** [comment]
Closed by #116
