### ISSUE TITLE
As a Canine Companions Researchers I want to use the outcome data to generate graphs on dogs by region so I can see how my dogs are performing by region

### ISSUE THREAD

**Issue by william7hsu** [ChelsiAlise/workingdogdatadash#28]
# **Story/Task Detail**
- [x]  Able to use outcome data to generate graphs.

- [x] Able to see dogs by regions

# **Acceptance Scenarios**

Given: a researcher clicks dog name.

When: The researcher clicks the generate graph button

Then: The outcome data is graphed with region information.

Given: A researcher clicks invalid data/

When: The researcher clicks the generate graph button.

Then: A prompt will say invalid data

# **Acceptance Scenarios**
The client is able to use the outcome data to generate graphs as well as get information about regions information

**Comment by BenTheElder** [comment]
This data is live on the server if you hadn't noticed. We just need to actually use/display it.
See #41, #45, #53.
