### ISSUE TITLE
As a Canine Companions Researchers I want to use the outcome data and organize it by region so I can see how my dogs are performing 

### ISSUE THREAD

**Issue by william7hsu** [ChelsiAlise/workingdogdatadash#29]
# **Story/Task Detail**
- [ ] Able to see dogs by regions

# **Acceptance Scenarios**

Given: a researcher clicks dog name.

When: The researcher clicks the information button

Then: The dog's region data is shown.

# **Done Done Criteria**
The client is able to view region data of dgos

**Comment by ChelsiAlise** [comment]
This is a duplicate issue: *CLOSING*
