### ISSUE TITLE
As a Canine Companions Researchers I want to select specific data attributes so I can perform statistical calculations (like t tests,p values, etc.) within the system 

### ISSUE THREAD

**Issue by ChelsiAlise** [ChelsiAlise/workingdogdatadash#30]
# Story/Task Detail

- [x]  Able to enter specific data attributes in order to perform statistical calculations (think R style functionality)
- [ ] Ability to perform t-tests
- [ ] Ability to perform p-values
- [ ] Ability to perform pair y's etc.

# Acceptance Scenarios

Given: a researcher can access another tab at the side of the dashboard in order to get to the statistical analysis area of the system

When: The researcher choose which type of statistics calculation they want to do (example: p-value calculation)

Then: A form to enter all the data they need to do the calculations is shown

Given: A researcher enters all the values correctly

When: The researcher clicks perform calculation button

Then: the result of the calculation should be shown 
# 
Acceptance Scenarios Test

The client is able to use the outcome data to do statistical calculations.  

# Done Done Criteria

Functionality tested, code has been merged into master.

**Comment by BenTheElder** [comment]
Was this closed by #68 ?

**Comment by ChelsiAlise** [comment]
Deliverable delivered to Joelle to the best of our capacity. Closing issue.
