### ISSUE TITLE
As a Canine Companions Researchers I want to use the outcome data so I can see my high activity dogs vs. my low activity dogs 

### ISSUE THREAD

**Issue by ChelsiAlise** [ChelsiAlise/workingdogdatadash#31]
# Story/Task Detail

- [ ]  Able to see high activity dogs vs. low activity dogs from outcome data

# Acceptance Scenarios

Given: a researcher clicks dog name.

When: The researcher clicks the information button

Then: The dog's activity data is shown as either low or high

# Done Done Criteria

Functionality tested. The client is able to view high activity vs. low activity dogs. Code merged to master.

**Comment by BenTheElder** [comment]
This needs clarifying, we can already see high vs. low activity dogs.

**Comment by ChelsiAlise** [comment]
They no longer want this feature. Closing issue.
