### ISSUE TITLE
Loading dog data first for ease of graph creation.

### ISSUE THREAD

**Issue by william7hsu** [ChelsiAlise/workingdogdatadash#59]
# Story/Task Detail

Adding the ability to load dog data first before graph creation.

# Acceptance Scenarios

TBD

# Done Done Criteria

TBD

**Comment by ChelsiAlise** [comment]
Ability to add multiple trendlines to line graphs should be included in this.

**Comment by BenTheElder** [comment]
What does this cover exactly? The dog data _is_ loaded first, and then what is currently the full data set.

If you do mean something else, the hooks for doing this sort of thing are in index.js `loadDataAndInitialize`, and the global cached vars are at the top of the script.

**Comment by BenTheElder** [comment]
This needs to be filled out but it should be done already by #58.
